name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: npm install
        
      - name: Build and start the server 
        run: npm start
    outputs:
        success: true
